[project]
name = "forked-sd-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate==0.30.0",
    "transformers==4.44.0",
    "diffusers[torch]==0.25.0",
    "ftfy==6.1.1",
    "opencv-python==4.8.1.78",
    "einops==0.7.0",
    "pytorch-lightning==1.9.0",
    "bitsandbytes==0.44.0",
    "prodigyopt==1.0",
    "lion-pytorch==0.0.6",
    "tensorboard",
    "safetensors==0.4.2",
    "altair==4.2.2",
    "easygui==0.98.3",
    "toml==0.10.2",
    "voluptuous==0.13.1",
    "huggingface-hub==0.24.5",
    "imagesize==1.4.1",
    "onnx==1.15.0",
    "onnxruntime-gpu",
    "rich==13.7.0",
]


[tool.uv]
environments = ["platform_machine == 'x86_64' and sys_platform == 'linux'"]


[[tool.uv.index]]
name = "onnxruntime-cuda-12"
url = "https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/"
explicit = true


[tool.uv.sources]
onnxruntime-gpu = { index = "onnxruntime-cuda-12" }
